update tips set node1 = 'Mabe Village', node2 = '0x2A4', difficulty = 0 where connection_id = '0';
update tips set node1 = 'Mabe Village', node2 = '0x0A3', difficulty = 0 where connection_id = '2';
update tips set node1 = 'Mabe Village', node2 = '0x0D2', difficulty = 0 where connection_id = '3';
update tips set node1 = 'Mabe Village', node2 = '0x092', difficulty = 0 where connection_id = '4';
update tips set node1 = 'Mabe Village', node2 = '0x0D3', difficulty = 0 where connection_id = '5';
update tips set node1 = 'Rooster Cave', node2 = '0x1E4', difficulty = 0 where connection_id = '6';
update tips set node1 = 'Papahl House', node2 = '0x2A6-Trade', difficulty = 0 where connection_id = '7';
update tips set node1 = 'Trendy Shop', node2 = '0x2A0-Trade', difficulty = 0 where connection_id = '8';
update tips set node1 = 'Mabe Village', node2 = 'Unnamed - Mabe Village', difficulty = 0 where connection_id = '9';
update tips set node1 = 'Boots ''n'' Bomb Cave', node2 = '0x2F4', difficulty = 0 where connection_id = '10';
update tips set node1 = 'Boots ''n'' Bomb Cave', node2 = '0x2E5', difficulty = 0 where connection_id = '11';
update tips set node1 = 'Mamu', node2 = '0x2FB', difficulty = 0 where connection_id = '13';
update tips set node1 = 'Ukuku Prairie', node2 = 'Outside D3', difficulty = 0 where connection_id = '14';
update tips set node1 = 'Outside D3', node2 = '0x0A5', difficulty = 0 where connection_id = '16';
update tips set node1 = 'Outside D3', node2 = 'Ukuku Prairie', difficulty = 0 where connection_id = '17';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0A6', difficulty = 0 where connection_id = '18';
update tips set node1 = 'Ukuku Prairie', node2 = '0x08B', difficulty = 0 where connection_id = '19';
update tips set node1 = 'Near Slime Key', node2 = '0x0C6-Owl', difficulty = 0 where connection_id = '20';
update tips set node1 = 'Near Slime Key', node2 = '0x0C6', difficulty = 0 where connection_id = '21';
update tips set node1 = 'Ukuku Prairie', node2 = 'Next to Kanalet', difficulty = 0 where connection_id = '24';
update tips set node1 = 'Kanalet Tunnel East', node2 = 'Kanalet Tunnel West', difficulty = 0 where connection_id = '26';
update tips set node1 = 'Kanalet Courtyard', node2 = 'Kanalet Front Door', difficulty = 0 where connection_id = '27';
update tips set node1 = 'Ukuku Prairie', node2 = 'Kanalet Front Door', difficulty = 0 where connection_id = '28';
update tips set node1 = 'Armos Maze', node2 = 'Outside Armos Maze Cave', difficulty = 0 where connection_id = '30';
update tips set node1 = 'Armos Maze', node2 = 'Outside Southern Shrine', difficulty = 0 where connection_id = '31';
update tips set node1 = 'Bay Water', node2 = 'Outside D6 Fairy', difficulty = 0 where connection_id = '32';
update tips set node1 = 'Animal Village', node2 = 'Outside D6 Fairy', difficulty = 0 where connection_id = '33';
update tips set node1 = 'To D6 East', node2 = 'To D6 West', difficulty = 0 where connection_id = '35';
update tips set node1 = 'Outside D6', node2 = 'Bay Water', difficulty = 0 where connection_id = '36';
update tips set node1 = 'Outside D6', node2 = '0x08C', difficulty = 0 where connection_id = '37';
update tips set node1 = 'Bay Water', node2 = 'Armos Island', difficulty = 0 where connection_id = '38';
update tips set node1 = 'Raft Return South', node2 = 'Raft Return North', difficulty = 0 where connection_id = '40';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Outside Raft House', difficulty = 0 where connection_id = '41';
update tips set node1 = 'Outside Raft House', node2 = 'Near D4 Keyhole', difficulty = 0 where connection_id = '42';
update tips set node1 = 'Outside Raft House', node2 = '0x05C', difficulty = 0 where connection_id = '43';
update tips set node1 = '0x05C', node2 = 'Raft Exit', difficulty = 1 where connection_id = '44';
update tips set node1 = '0x05C', node2 = 'Outside D6 Fairy', difficulty = 1 where connection_id = '45';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Raft Exit', difficulty = 0 where connection_id = '46';
update tips set node1 = 'Lower Tal Tal', node2 = 'Between Waterfall and Mountain Stairs', difficulty = 0 where connection_id = '47';
update tips set node1 = 'Between Waterfall and Mountain Stairs', node2 = 'Outside Rooster House', difficulty = 0 where connection_id = '48';
update tips set node1 = 'Bird Cave', node2 = '0x27A', difficulty = 0 where connection_id = '49';
update tips set node1 = 'Outside D8', node2 = 'Outside Fire Cave', difficulty = 1 where connection_id = '50';
update tips set node1 = 'Nightmare', node2 = 'Windfish', difficulty = 0 where connection_id = '53';
update tips set node1 = 'Hookshot Cave', node2 = '0x2B3', difficulty = 2 where connection_id = '54';
update tips set node1 = 'Graveyard Cave West', node2 = 'Graveyard Cave East', difficulty = 2 where connection_id = '55';
update tips set node1 = 'Swamp', node2 = 'Swamp Chest', difficulty = 2 where connection_id = '56';
update tips set node1 = 'Swamp', node2 = 'Unnamed - Swamp,D2 Entrance', difficulty = 2 where connection_id = '57';
update tips set node1 = 'Unnamed - Swamp,D2 Entrance', node2 = 'Swamp', difficulty = 2 where connection_id = '59';
update tips set node1 = 'Graveyard', node2 = 'Forest Heart Piece', difficulty = 3 where connection_id = '60';
update tips set node1 = 'Graveyard', node2 = 'Forest', difficulty = 3 where connection_id = '61';
update tips set node1 = 'Forest Cave', node2 = '0x2AB', difficulty = 3 where connection_id = '63';
update tips set node1 = 'Graveyard Cave West', node2 = '0x2DF', difficulty = 3 where connection_id = '64';
update tips set node1 = 'Graveyard Cave East', node2 = '0x2DF', difficulty = 3 where connection_id = '65';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0A6', difficulty = 3 where connection_id = '66';
update tips set node1 = 'Ukuku Prairie', node2 = '0x1FD', difficulty = 3 where connection_id = '67';
update tips set node1 = 'Outside Ghost House', node2 = 'Western Bay', difficulty = 3 where connection_id = '68';
update tips set node1 = 'Western Bay', node2 = '0x0F8', difficulty = 3 where connection_id = '69';
update tips set node1 = 'Lower Tal Tal', node2 = 'Outside Rooster House', difficulty = 3 where connection_id = '70';
update tips set node1 = 'D7 Plateau', node2 = 'Near Hole to Damp Cave', difficulty = 3 where connection_id = '71';
update tips set node1 = 'Near Hole to Damp Cave', node2 = 'Damp Cave', difficulty = 3 where connection_id = '72';
update tips set node1 = 'Outside Rooster House', node2 = 'Bridge Towards D8', difficulty = 3 where connection_id = '73';
update tips set node1 = 'Bird Cave', node2 = '0x27A', difficulty = 3 where connection_id = '74';
update tips set node1 = 'Inner Rainbow Cave Entrance', node2 = 'Inner Rainbow Cave Exit', difficulty = 3 where connection_id = '75';
update tips set node1 = 'Path to West Tal Tal Exit', node2 = 'Path to West Tal Tal Entrance', difficulty = 3 where connection_id = '76';
update tips set node1 = 'Mountain Access Inside', node2 = '0x2BA', difficulty = 3 where connection_id = '77';
update tips set node1 = 'Outside D8', node2 = 'D8 Entrance', difficulty = 3 where connection_id = '78';
update tips set node1 = 'Dream Hut', node2 = '0x2BF', difficulty = 4 where connection_id = '79';
update tips set node1 = 'Bay Water', node2 = 'Outside D5', difficulty = 4 where connection_id = '80';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0A6', difficulty = 4 where connection_id = '81';
update tips set node1 = 'Bay Batter Tunnel Exit', node2 = 'Bay Batter Tunnel Entrance', difficulty = 4 where connection_id = '82';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Next to Kanalet', difficulty = 4 where connection_id = '84';
update tips set node1 = 'Kanalet Courtyard', node2 = '0x058', difficulty = 4 where connection_id = '85';
update tips set node1 = 'Animal Village', node2 = 'Inside Mermaid Statue', difficulty = 4 where connection_id = '86';
update tips set node1 = 'Under the River East', node2 = 'Under the River West', difficulty = 4 where connection_id = '87';
update tips set node1 = 'Under the River West', node2 = 'Under the River East', difficulty = 4 where connection_id = '88';
update tips set node1 = 'Bomb Arrow Cave', node2 = '0x2E6', difficulty = 4 where connection_id = '89';
update tips set node1 = 'Inner Rainbow Cave Entrance', node2 = 'Inner Rainbow Cave Exit', difficulty = 4 where connection_id = '90';
update tips set node1 = 'Near Hole to Damp Cave', node2 = 'Damp Cave', difficulty = 4 where connection_id = '91';
update tips set node1 = 'Outside Rooster House', node2 = 'Bridge Towards D8', difficulty = 4 where connection_id = '92';
update tips set node1 = 'Path to West Tal Tal Entrance', node2 = 'Path to West Tal Tal Exit', difficulty = 4 where connection_id = '93';
update tips set node1 = 'Path to West Tal Tal Exit', node2 = 'Path to West Tal Tal Entrance', difficulty = 4 where connection_id = '94';
update tips set node1 = 'Nightmare', node2 = 'Windfish', difficulty = 4 where connection_id = '95';
update tips set node1 = 'Start House', node2 = 'Outside Crazy Tracy''s House', difficulty = 0 where connection_id = '02';
update tips set node1 = 'Start House', node2 = 'Mabe Village', difficulty = 0 where connection_id = 'start_house';
update tips set node1 = 'Outside Crazy Tracy''s House', node2 = 'Forest', difficulty = 0 where connection_id = '00';
update tips set node1 = 'Outside Crazy Tracy''s House', node2 = 'Crazy Tracy''s House', difficulty = 0 where connection_id = 'crazy_tracy';
update tips set node1 = 'Graveyard', node2 = 'Outside Crazy Tracy''s House', difficulty = 4 where connection_id = '7i';
update tips set node1 = 'Forest', node2 = 'Mabe Village', difficulty = 0 where connection_id = 'w';
update tips set node1 = 'Forest', node2 = '0x071', difficulty = 0 where connection_id = 'x';
update tips set node1 = 'Forest', node2 = 'Forest Heart Piece', difficulty = 0 where connection_id = 'y';
update tips set node1 = 'Forest', node2 = 'Swamp', difficulty = 0 where connection_id = '08';
update tips set node1 = 'Forest', node2 = 'Graveyard', difficulty = 0 where connection_id = '0j';
update tips set node1 = 'Forest', node2 = 'Ghost Grave', difficulty = 0 where connection_id = '0l';
update tips set node1 = 'Forest', node2 = 'Hookshot Cave', difficulty = 0 where connection_id = 'hookshot_cave';
update tips set node1 = 'Forest', node2 = 'Forest Mad Batter', difficulty = 0 where connection_id = 'forest_madbatter';
update tips set node1 = 'Forest', node2 = 'Forest Cave', difficulty = 0 where connection_id = 'toadstool_entrance';
update tips set node1 = 'Forest', node2 = 'Witch''s Hut', difficulty = 0 where connection_id = 'witch';
update tips set node1 = 'Forest', node2 = 'Forest Heart Piece', difficulty = 3 where connection_id = '5w';
update tips set node1 = 'Forest', node2 = 'Swamp', difficulty = 3 where connection_id = '5v';
update tips set node1 = 'Forest', node2 = 'Hookshot Cave', difficulty = 3 where connection_id = '5x';
update tips set node1 = 'Forest', node2 = 'Forest Heart Piece', difficulty = 4 where connection_id = '7c';
update tips set node1 = 'Forest', node2 = 'Swamp', difficulty = 4 where connection_id = '7b';
update tips set node1 = 'Forest', node2 = 'Graveyard', difficulty = 4 where connection_id = '7j';
update tips set node1 = 'Swamp', node2 = 'Forest', difficulty = 0 where connection_id = '09';
update tips set node1 = 'Forest Mad Batter', node2 = 'Forest', difficulty = 0 where connection_id = 'null';
update tips set node1 = 'Mabe Village', node2 = '0x2B1', difficulty = 0 where connection_id = 'tracker-d';
update tips set node1 = 'Mabe Village', node2 = 'Unnamed - Mabe Village,Dream Hut', difficulty = 0 where connection_id = 'k';
update tips set node1 = 'Mabe Village', node2 = 'Sword Beach', difficulty = 0 where connection_id = 'n';
update tips set node1 = 'Mabe Village', node2 = 'Ukuku Prairie', difficulty = 0 where connection_id = '0s';
update tips set node1 = 'Mabe Village', node2 = 'Papahl House', difficulty = 0 where connection_id = 'papahl_house_right';
update tips set node1 = 'Mabe Village', node2 = 'Rooster Cave', difficulty = 0 where connection_id = 'rooster_grave';
update tips set node1 = 'Mabe Village', node2 = 'Shop', difficulty = 0 where connection_id = 'shop';
update tips set node1 = 'Mabe Village', node2 = 'Unnamed - Mabe Village', difficulty = 0 where connection_id = 'madambowwow';
update tips set node1 = 'Mabe Village', node2 = 'Kennel', difficulty = 0 where connection_id = 'kennel';
update tips set node1 = 'Mabe Village', node2 = 'Library', difficulty = 0 where connection_id = 'library';
update tips set node1 = 'Mabe Village', node2 = 'Trendy Shop', difficulty = 0 where connection_id = 'trendy_shop';
update tips set node1 = 'Mabe Village', node2 = 'D1 Entrance', difficulty = 0 where connection_id = 'd1';
update tips set node1 = 'Mabe Village', node2 = 'Unnamed - Mabe Village,Dream Hut', difficulty = 3 where connection_id = '5t';
update tips set node1 = 'Unnamed - Mabe Village,Dream Hut', node2 = 'Dream Hut', difficulty = 0 where connection_id = 'dream_hut';
update tips set node1 = 'Dream Hut', node2 = '0x2BF', difficulty = 0 where connection_id = 'h';
update tips set node1 = 'Dream Hut', node2 = '0x2BF', difficulty = 1 where connection_id = 'i';
update tips set node1 = '0x2BF', node2 = '0x2BE', difficulty = 0 where connection_id = 'j';
update tips set node1 = '0x2BF', node2 = '0x2BE', difficulty = 3 where connection_id = '5u';
update tips set node1 = 'Sword Beach', node2 = 'Unnamed - Banana Seller,Sword Beach', difficulty = 0 where connection_id = 'p';
update tips set node1 = 'Sword Beach', node2 = 'Sword Beach to Ghost House', difficulty = 0 where connection_id = 't';
update tips set node1 = 'Sword Beach', node2 = 'Boomerang Cave', difficulty = 0 where connection_id = 'boomerang_cave';
update tips set node1 = 'Unnamed - Banana Seller,Sword Beach', node2 = 'Banana Seller', difficulty = 0 where connection_id = 'banana_seller';
update tips set node1 = 'Banana Seller', node2 = '0x2FE-Trade', difficulty = 0 where connection_id = 'o';
update tips set node1 = 'Sword Beach to Ghost House', node2 = 'Outside Ghost House', difficulty = 0 where connection_id = 'u';
update tips set node1 = 'Outside Ghost House', node2 = 'Western Bay', difficulty = 0 where connection_id = '1d';
update tips set node1 = 'Outside Ghost House', node2 = 'Ghost House', difficulty = 0 where connection_id = 'ghost_house';
update tips set node1 = 'Outside Ghost House', node2 = 'Western Bay', difficulty = 4 where connection_id = '7r';
update tips set node1 = 'Western Bay', node2 = '0x0E9', difficulty = 0 where connection_id = '1f';
update tips set node1 = 'Western Bay', node2 = '0x0F8', difficulty = 0 where connection_id = '1g';
update tips set node1 = 'Western Bay', node2 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', difficulty = 0 where connection_id = '1m';
update tips set node1 = 'Western Bay', node2 = 'Bay Water', difficulty = 0 where connection_id = '1s';
update tips set node1 = 'Western Bay', node2 = 'Bay Cliff Cave', difficulty = 0 where connection_id = 'prairie_right_cave_bottom';
update tips set node1 = 'Western Bay', node2 = 'Unnamed - Western Bay', difficulty = 0 where connection_id = 'prairie_low_phone';
update tips set node1 = 'Western Bay', node2 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', difficulty = 2 where connection_id = '5e';
update tips set node1 = 'Western Bay', node2 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', difficulty = 3 where connection_id = '6b';
update tips set node1 = 'Western Bay', node2 = '0x0F8', difficulty = 4 where connection_id = '7t';
update tips set node1 = 'Western Bay', node2 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', difficulty = 4 where connection_id = '7v';
update tips set node1 = 'Western Bay', node2 = 'Bay Water', difficulty = 4 where connection_id = '7x';
update tips set node1 = 'Western Bay', node2 = 'Ukuku Prairie', difficulty = 4 where connection_id = '7s';
update tips set node1 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', node2 = 'Western Bay', difficulty = 0 where connection_id = '1n';
update tips set node1 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', node2 = 'Western Bay', difficulty = 4 where connection_id = '7w';
update tips set node1 = 'Unnamed - Bay Batter Tunnel Entrance,Western Bay', node2 = 'Bay Batter Tunnel Entrance', difficulty = 0 where connection_id = 'prairie_madbatter_connector_entrance';
update tips set node1 = 'Bay Batter Tunnel Entrance', node2 = 'Bay Batter Tunnel Exit', difficulty = 0 where connection_id = '1k';
update tips set node1 = 'Bay Batter Tunnel Exit', node2 = 'Bay Batter Tunnel Entrance', difficulty = 3 where connection_id = '6a';
update tips set node1 = 'Bay Batter Tunnel Exit', node2 = 'Outside Bay Batter', difficulty = 0 where connection_id = 'prairie_madbatter_connector_exit';
update tips set node1 = 'Outside Bay Batter', node2 = 'Bay Batter', difficulty = 0 where connection_id = 'prairie_madbatter';
update tips set node1 = 'Bay Batter', node2 = '0x1E0', difficulty = 0 where connection_id = '1l';
update tips set node1 = 'Bay Water', node2 = 'Ukuku Prairie', difficulty = 0 where connection_id = '1r';
update tips set node1 = 'Bay Water', node2 = '0x2F5-Trade', difficulty = 0 where connection_id = '1t';
update tips set node1 = 'Bay Water', node2 = '0x0C9-Trade', difficulty = 0 where connection_id = '1u';
update tips set node1 = 'Bay Water', node2 = 'Outside D5', difficulty = 0 where connection_id = '1v';
update tips set node1 = 'Bay Water', node2 = '0x078', difficulty = 0 where connection_id = '2a';
update tips set node1 = 'Bay Water', node2 = 'Animal Village', difficulty = 0 where connection_id = '2m';
update tips set node1 = 'Bay Water', node2 = 'Near D4 Keyhole', difficulty = 0 where connection_id = '3p';
update tips set node1 = 'Bay Water', node2 = '0x2F5-Trade', difficulty = 2 where connection_id = 'tracker-e';
update tips set node1 = 'Bay Water', node2 = '0x2F5-Trade', difficulty = 3 where connection_id = 'tracker-f';
update tips set node1 = 'Bay Water', node2 = 'Animal Village', difficulty = 4 where connection_id = '7y';
update tips set node1 = 'Ukuku Prairie', node2 = 'Bay Water', difficulty = 4 where connection_id = '7z';
update tips set node1 = 'Ukuku Prairie', node2 = 'Graveyard', difficulty = 0 where connection_id = '0t';
update tips set node1 = 'Ukuku Prairie', node2 = '0x07B-Trade', difficulty = 0 where connection_id = '0u';
update tips set node1 = 'Ukuku Prairie', node2 = '0x087-Trade', difficulty = 0 where connection_id = '0v';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0B5', difficulty = 0 where connection_id = '0w';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0A4', difficulty = 0 where connection_id = '1a';
update tips set node1 = 'Ukuku Prairie', node2 = '0x0B9', difficulty = 0 where connection_id = '1c';
update tips set node1 = 'Ukuku Prairie', node2 = 'Animal Village', difficulty = 0 where connection_id = '2n';
update tips set node1 = 'Ukuku Prairie', node2 = '0x1FD', difficulty = 0 where connection_id = 'castle_jump_cave';
update tips set node1 = 'Ukuku Prairie', node2 = 'Unnamed - Ukuku Prairie', difficulty = 0 where connection_id = 'prairie_left_phone';
update tips set node1 = 'Ukuku Prairie', node2 = '0x2CD', difficulty = 0 where connection_id = 'prairie_left_cave1';
update tips set node1 = 'Ukuku Prairie', node2 = 'Boots ''n'' Bomb Cave', difficulty = 0 where connection_id = 'prairie_left_cave2';
update tips set node1 = 'Ukuku Prairie', node2 = 'Unnamed - Ukuku Prairie', difficulty = 0 where connection_id = 'prairie_left_fairy';
update tips set node1 = 'Ukuku Prairie', node2 = 'Mamu', difficulty = 0 where connection_id = 'mamu';
update tips set node1 = 'Ukuku Prairie', node2 = 'Seashell Mansion', difficulty = 0 where connection_id = 'seashell_mansion';
update tips set node1 = 'Ukuku Prairie', node2 = 'Bay Cliff Cave', difficulty = 0 where connection_id = 'prairie_right_cave_top';
update tips set node1 = 'Ukuku Prairie', node2 = 'Under the River West', difficulty = 0 where connection_id = 'prairie_to_animal_connector';
update tips set node1 = 'Ukuku Prairie', node2 = 'Richard''s Villa', difficulty = 0 where connection_id = 'richard_house';
update tips set node1 = 'Ukuku Prairie', node2 = 'RiverRooster', difficulty = 0 where connection_id = 'tracker-q';
update tips set node1 = 'Ukuku Prairie', node2 = 'Mamu', difficulty = 2 where connection_id = '5d';
update tips set node1 = 'Ukuku Prairie', node2 = 'Animal Village', difficulty = 3 where connection_id = '6f';
update tips set node1 = 'Ukuku Prairie', node2 = 'Pothole Maze', difficulty = 3 where connection_id = '6c';
update tips set node1 = 'Ukuku Prairie', node2 = 'Armos Island', difficulty = 4 where connection_id = '8a';
update tips set node1 = 'Ukuku Prairie', node2 = '0x1FD', difficulty = 4 where connection_id = '7n';
update tips set node1 = 'Ukuku Prairie', node2 = 'Mamu', difficulty = 4 where connection_id = '7m';
update tips set node1 = 'Pothole Maze', node2 = 'Ukuku Prairie', difficulty = 3 where connection_id = '6d';
update tips set node1 = 'Outside D6', node2 = 'Ukuku Prairie', difficulty = 3 where connection_id = '6j';
update tips set node1 = 'Outside D6', node2 = 'Ukuku Prairie', difficulty = 4 where connection_id = '8d';
update tips set node1 = 'Graveyard', node2 = 'Forest Heart Piece', difficulty = 0 where connection_id = '0n';
update tips set node1 = 'Graveyard', node2 = 'Outside the Egg', difficulty = 0 where connection_id = '3b';
update tips set node1 = 'Graveyard', node2 = 'Moblin Cave', difficulty = 0 where connection_id = 'moblin_cave';
update tips set node1 = 'Graveyard', node2 = 'Unnamed - Graveyard', difficulty = 0 where connection_id = 'photo_house';
update tips set node1 = 'Graveyard', node2 = 'Graveyard Cave East', difficulty = 0 where connection_id = 'graveyard_cave_right';
update tips set node1 = 'Graveyard', node2 = 'D0 Entrance', difficulty = 0 where connection_id = 'd0';
update tips set node1 = 'Outside the Egg', node2 = 'Graveyard', difficulty = 0 where connection_id = '3c';
update tips set node1 = 'Outside the Egg', node2 = 'Swamp', difficulty = 0 where connection_id = '3a';
update tips set node1 = 'Outside the Egg', node2 = 'Unnamed - Mountain Access Entrance,Outside the Egg', difficulty = 0 where connection_id = '3h';
update tips set node1 = 'Outside the Egg', node2 = 'Near D4 Keyhole', difficulty = 0 where connection_id = '3k';
update tips set node1 = 'Outside the Egg', node2 = 'Unnamed - Mountain Access Entrance,Outside the Egg', difficulty = 3 where connection_id = '6o';
update tips set node1 = 'Bridge Towards D8', node2 = 'Outside the Egg', difficulty = 1 where connection_id = '4p';
update tips set node1 = 'Swamp', node2 = '0x050', difficulty = 0 where connection_id = '0a';
update tips set node1 = 'Swamp', node2 = 'Swamp Chest', difficulty = 0 where connection_id = '0b';
update tips set node1 = 'Swamp', node2 = 'Unnamed - Swamp,D2 Entrance', difficulty = 0 where connection_id = '0c';
update tips set node1 = 'Swamp', node2 = '0x041', difficulty = 0 where connection_id = '0d';
update tips set node1 = 'Swamp', node2 = 'Outside Write''s House', difficulty = 0 where connection_id = '0f';
update tips set node1 = 'Swamp', node2 = 'Unnamed - Swamp', difficulty = 0 where connection_id = 'writes_phone';
update tips set node1 = 'Swamp', node2 = 'Outside Write''s House', difficulty = 2 where connection_id = '5a';
update tips set node1 = 'Swamp', node2 = '0x050', difficulty = 3 where connection_id = '5y';
update tips set node1 = 'Swamp', node2 = '0x050', difficulty = 4 where connection_id = '7a';
update tips set node1 = 'Swamp', node2 = 'Outside Write''s House', difficulty = 4 where connection_id = '7g';
update tips set node1 = 'Outside Write''s House', node2 = 'Swamp', difficulty = 3 where connection_id = '5z';
update tips set node1 = '0x050', node2 = 'Forest Cave', difficulty = 0 where connection_id = 'toadstool_exit';
update tips set node1 = 'Forest Cave', node2 = '0x2BD', difficulty = 0 where connection_id = '05';
update tips set node1 = 'Forest Cave', node2 = '0x2AB', difficulty = 0 where connection_id = '06';
update tips set node1 = 'Forest Cave', node2 = '0x2BD', difficulty = 4 where connection_id = '7d';
update tips set node1 = 'Forest Cave', node2 = '0x2AB', difficulty = 4 where connection_id = '7f';
update tips set node1 = 'Unnamed - Swamp,D2 Entrance', node2 = 'D2 Entrance', difficulty = 0 where connection_id = 'd2';
update tips set node1 = 'D2 Entrance', node2 = '0x136', difficulty = 0 where connection_id = 'bv';
update tips set node1 = 'D2 Entrance', node2 = 'D2 Left Door', difficulty = 0 where connection_id = 'bw';
update tips set node1 = 'D2 Entrance', node2 = 'D2 After Torches', difficulty = 0 where connection_id = 'by';
update tips set node1 = 'D2 Left Door', node2 = '0x12E', difficulty = 0 where connection_id = 'bx';
update tips set node1 = 'D2 Left Door', node2 = '0x12E', difficulty = 4 where connection_id = 'cm';
update tips set node1 = 'D2 After Torches', node2 = '0x132', difficulty = 0 where connection_id = 'bz';
update tips set node1 = 'D2 After Torches', node2 = '0x137', difficulty = 0 where connection_id = 'c0';
update tips set node1 = 'D2 After Torches', node2 = '0x133-Owl', difficulty = 0 where connection_id = 'c1';
update tips set node1 = 'D2 After Torches', node2 = '0x138', difficulty = 0 where connection_id = 'c2';
update tips set node1 = '0x138', node2 = '0x139', difficulty = 0 where connection_id = 'c3';
update tips set node1 = '0x138', node2 = '0x134', difficulty = 0 where connection_id = 'c4';
update tips set node1 = '0x138', node2 = '0x134', difficulty = 1 where connection_id = 'c5';
update tips set node1 = '0x138', node2 = '0x139', difficulty = 4 where connection_id = 'cn';
update tips set node1 = '0x139', node2 = 'D2 Pushblock Room', difficulty = 0 where connection_id = 'c6';
update tips set node1 = '0x139', node2 = '0x1392', difficulty = 0 where connection_id = 'tracker-k';
update tips set node1 = '0x139', node2 = '0x134', difficulty = 4 where connection_id = 'co';
update tips set node1 = 'D2 Pushblock Room', node2 = '0x12F-Owl', difficulty = 0 where connection_id = 'c7';
update tips set node1 = 'D2 Pushblock Room', node2 = 'D2 Miniboss Room', difficulty = 0 where connection_id = 'c8';
update tips set node1 = 'D2 Pushblock Room', node2 = 'D2 Miniboss Room', difficulty = 4 where connection_id = 'cp';
update tips set node1 = 'D2 Miniboss Room', node2 = '0x126', difficulty = 0 where connection_id = 'c9';
update tips set node1 = '0x126', node2 = '0x129-Owl', difficulty = 0 where connection_id = 'ca';
update tips set node1 = '0x126', node2 = 'D2 Boo Buddies Room', difficulty = 0 where connection_id = 'cb';
update tips set node1 = '0x126', node2 = 'D2 After Boo Buddies', difficulty = 0 where connection_id = 'cd';
update tips set node1 = '0x126', node2 = '0x1212', difficulty = 0 where connection_id = 'tracker-l';
update tips set node1 = '0x126', node2 = 'D2 After Boo Buddies', difficulty = 3 where connection_id = 'cl';
update tips set node1 = 'D2 Boo Buddies Room', node2 = '0x120', difficulty = 0 where connection_id = 'cc';
update tips set node1 = 'D2 Boo Buddies Room', node2 = '0x120', difficulty = 3 where connection_id = 'ck';
update tips set node1 = 'D2 After Boo Buddies', node2 = '0x127', difficulty = 0 where connection_id = 'ce';
update tips set node1 = 'D2 After Boo Buddies', node2 = 'D2 Before Boss Stairs', difficulty = 0 where connection_id = 'cf';
update tips set node1 = 'D2 After Boo Buddies', node2 = 'D2 Before Boss Stairs', difficulty = 4 where connection_id = 'cq';
update tips set node1 = 'D2 Before Boss Stairs', node2 = 'D2 Boss Stairs', difficulty = 0 where connection_id = 'cg';
update tips set node1 = 'D2 Before Boss Stairs', node2 = 'D2 Boss Stairs', difficulty = 4 where connection_id = 'cr';
update tips set node1 = 'D2 Boss Stairs', node2 = 'D2 Outside Boss Room', difficulty = 0 where connection_id = 'ch';
update tips set node1 = 'D2 Boss Stairs', node2 = 'D2 Outside Boss Room', difficulty = 4 where connection_id = 'cs';
update tips set node1 = 'D2 Outside Boss Room', node2 = 'D2 Boss Room', difficulty = 0 where connection_id = 'ci';
update tips set node1 = 'D2 Boss Room', node2 = '0x12B', difficulty = 0 where connection_id = 'cj';
update tips set node1 = 'Outside Write''s House', node2 = 'Write''s Cave', difficulty = 0 where connection_id = 'writes_cave_right';
update tips set node1 = 'Outside Write''s House', node2 = 'Write''s House', difficulty = 0 where connection_id = 'writes_house';
update tips set node1 = 'Outside Fire Cave', node2 = 'Outside Write''s House', difficulty = 1 where connection_id = '4v';
update tips set node1 = 'Outside D8', node2 = 'Outside Write''s House', difficulty = 1 where connection_id = '4z';
update tips set node1 = 'Write''s Cave', node2 = '0x2AE', difficulty = 0 where connection_id = '0h';
update tips set node1 = 'Write''s Cave', node2 = '0x2AF', difficulty = 0 where connection_id = '0i';
update tips set node1 = 'Write''s Cave', node2 = '0x2AE', difficulty = 4 where connection_id = '7h';
update tips set node1 = 'Write''s House', node2 = '0x2A8-Trade', difficulty = 0 where connection_id = '0g';
update tips set node1 = 'Unnamed - Mountain Access Entrance,Outside the Egg', node2 = 'Mountain Access Entrance', difficulty = 0 where connection_id = 'obstacle_cave_entrance';
update tips set node1 = 'Mountain Access Entrance', node2 = 'Mountain Access Inside', difficulty = 0 where connection_id = '3d';
update tips set node1 = 'Mountain Access Entrance', node2 = 'Mountain Access Inside', difficulty = 4 where connection_id = '8i';
update tips set node1 = 'Mountain Access Inside', node2 = 'Mountain Access Entrance', difficulty = 0 where connection_id = '3e';
update tips set node1 = 'Mountain Access Inside', node2 = '0x2BB', difficulty = 0 where connection_id = '3f';
update tips set node1 = 'Mountain Access Inside', node2 = 'Mountain Access Exit', difficulty = 0 where connection_id = '3g';
update tips set node1 = 'Mountain Access Inside', node2 = '0x018', difficulty = 0 where connection_id = 'obstacle_cave_outside_chest';
update tips set node1 = 'Mountain Access Inside', node2 = '0x2BB', difficulty = 3 where connection_id = '6p';
update tips set node1 = 'Mountain Access Inside', node2 = 'Mountain Access Exit', difficulty = 3 where connection_id = '6q';
update tips set node1 = 'Mountain Access Exit', node2 = 'Mountain Access Inside', difficulty = 2 where connection_id = '5n';
update tips set node1 = 'Mountain Access Exit', node2 = 'Lower Tal Tal', difficulty = 0 where connection_id = 'obstacle_cave_exit';
update tips set node1 = 'Lower Tal Tal', node2 = 'Outside D4 Closed', difficulty = 0 where connection_id = '3r';
update tips set node1 = 'Lower Tal Tal', node2 = 'Outside D4 Open', difficulty = 0 where connection_id = '3s';
update tips set node1 = 'Lower Tal Tal', node2 = 'Unnamed - Lower Tal Tal,5 Chest Game Tunnel', difficulty = 0 where connection_id = '4g';
update tips set node1 = 'Lower Tal Tal', node2 = '0x28A', difficulty = 0 where connection_id = 'papahl_entrance';
update tips set node1 = 'Lower Tal Tal', node2 = 'Outside D4 Closed', difficulty = 3 where connection_id = '6s';
update tips set node1 = 'Lower Tal Tal', node2 = 'Unnamed - Lower Tal Tal,5 Chest Game Tunnel', difficulty = 3 where connection_id = '6z';
update tips set node1 = 'Lower Tal Tal', node2 = '0x019-Trade', difficulty = 3 where connection_id = '6r';
update tips set node1 = 'Lower Tal Tal', node2 = 'Unnamed - Lower Tal Tal,5 Chest Game Tunnel', difficulty = 4 where connection_id = '8t';
update tips set node1 = 'Lower Tal Tal', node2 = 'D4 Keyhole', difficulty = 4 where connection_id = '8m';
update tips set node1 = 'Lower Tal Tal', node2 = 'Near D4 Keyhole', difficulty = 4 where connection_id = '8o';
update tips set node1 = 'Bird Cave', node2 = 'Lower Tal Tal', difficulty = 1 where connection_id = '4b';
update tips set node1 = 'Papahl''s Ledge', node2 = 'Lower Tal Tal', difficulty = 0 where connection_id = '3i';
update tips set node1 = 'Outside D4 Closed', node2 = 'Near D4 Keyhole', difficulty = 0 where connection_id = '3m';
update tips set node1 = 'Outside D4 Closed', node2 = 'Outside D4 Open', difficulty = 0 where connection_id = '3n';
update tips set node1 = 'Outside D4 Closed', node2 = 'Outside Manbo', difficulty = 0 where connection_id = '3x';
update tips set node1 = 'Outside D4 Closed', node2 = 'D4 Entrance', difficulty = 0 where connection_id = 'd4';
update tips set node1 = 'Outside D4 Closed', node2 = 'Outside Manbo', difficulty = 3 where connection_id = '6x';
update tips set node1 = 'Outside D4 Closed', node2 = 'D4 Keyhole', difficulty = 3 where connection_id = '6u';
update tips set node1 = 'Outside D4 Closed', node2 = 'Near D4 Keyhole', difficulty = 4 where connection_id = '8j';
update tips set node1 = 'Outside D4 Closed', node2 = 'Outside Manbo', difficulty = 4 where connection_id = '8q';
update tips set node1 = 'Outside D4 Closed', node2 = 'D4 Keyhole', difficulty = 4 where connection_id = '8k';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Outside D4 Closed', difficulty = 3 where connection_id = '6v';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Outside D4 Closed', difficulty = 4 where connection_id = '8l';
update tips set node1 = 'Near D4 Keyhole', node2 = 'D4 Keyhole', difficulty = 0 where connection_id = '3o';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Next to Kanalet', difficulty = 0 where connection_id = '3q';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Unnamed - Near D4 Keyhole,Damp Cave', difficulty = 0 where connection_id = '3u';
update tips set node1 = 'Near D4 Keyhole', node2 = 'KanaletRooster', difficulty = 0 where connection_id = 'tracker-r';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Next to Kanalet', difficulty = 3 where connection_id = '6g';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Unnamed - Near D4 Keyhole,Damp Cave', difficulty = 3 where connection_id = '6w';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Unnamed - Near D4 Keyhole,Damp Cave', difficulty = 4 where connection_id = '8p';
update tips set node1 = 'Near D4 Keyhole', node2 = 'Outside Raft House', difficulty = 4 where connection_id = '8x';
update tips set node1 = 'Outside Raft House', node2 = 'Near D4 Keyhole', difficulty = 3 where connection_id = '6y';
update tips set node1 = 'Outside D4 Open', node2 = 'Near D4 Keyhole', difficulty = 0 where connection_id = '3w';
update tips set node1 = 'Outside Rooster House', node2 = 'Near D4 Keyhole', difficulty = 4 where connection_id = '8u';
update tips set node1 = 'D4 Keyhole', node2 = '0x02B', difficulty = 0 where connection_id = '3l';
update tips set node1 = 'Outside D4 Open', node2 = 'D4 Keyhole', difficulty = 2 where connection_id = '5o';
update tips set node1 = 'Between Waterfall and Mountain Stairs', node2 = 'D4 Keyhole', difficulty = 4 where connection_id = '8n';
update tips set node1 = 'Next to Kanalet', node2 = 'Kanalet Tunnel East', difficulty = 0 where connection_id = 'castle_secret_entrance';
update tips set node1 = 'Next to Kanalet', node2 = 'Unnamed - Next to Kanalet', difficulty = 0 where connection_id = 'castle_phone';
update tips set node1 = 'Next to Kanalet', node2 = 'KanaletRooster', difficulty = 0 where connection_id = 'tracker-s';
update tips set node1 = 'Kanalet Tunnel East', node2 = 'Kanalet Tunnel West', difficulty = 4 where connection_id = '7q';
update tips set node1 = 'Kanalet Tunnel West', node2 = 'Kanalet Courtyard', difficulty = 0 where connection_id = 'castle_secret_exit';
update tips set node1 = 'Kanalet Courtyard', node2 = '0x05A', difficulty = 0 where connection_id = '2c';
update tips set node1 = 'Kanalet Courtyard', node2 = '0x058', difficulty = 0 where connection_id = '2d';
update tips set node1 = 'Kanalet Courtyard', node2 = '0x058', difficulty = 2 where connection_id = '5f';
update tips set node1 = 'Kanalet Front Door', node2 = 'Inside Kanalet', difficulty = 0 where connection_id = 'castle_main_entrance';
update tips set node1 = 'Inside Kanalet', node2 = '0x2C3', difficulty = 0 where connection_id = '2b';
update tips set node1 = 'Inside Kanalet', node2 = '0x2D2', difficulty = 0 where connection_id = '2e';
update tips set node1 = 'Inside Kanalet', node2 = '0x2C5', difficulty = 0 where connection_id = '2f';
update tips set node1 = 'Inside Kanalet', node2 = 'Outside Top of Kanalet', difficulty = 0 where connection_id = 'castle_upper_left';
update tips set node1 = 'Inside Kanalet', node2 = '0x2C6', difficulty = 2 where connection_id = '5g';
update tips set node1 = 'Outside Top of Kanalet', node2 = 'Inside Top of Kanalet', difficulty = 0 where connection_id = 'castle_upper_right';
update tips set node1 = 'Inside Top of Kanalet', node2 = '0x2C6', difficulty = 0 where connection_id = '2g';
update tips set node1 = 'Unnamed - Near D4 Keyhole,Damp Cave', node2 = 'Damp Cave', difficulty = 0 where connection_id = 'heartpiece_swim_cave';
update tips set node1 = 'Damp Cave', node2 = '0x1F2', difficulty = 0 where connection_id = '3t';
update tips set node1 = 'Near Hole to Damp Cave', node2 = 'Damp Cave', difficulty = 1 where connection_id = '4f';
update tips set node1 = 'D7 Plateau', node2 = 'Damp Cave', difficulty = 1 where connection_id = '4m';
update tips set node1 = 'Outside Raft House', node2 = 'Raft Return North', difficulty = 0 where connection_id = 'raft_return_exit';
update tips set node1 = 'Outside Raft House', node2 = 'Raft House', difficulty = 0 where connection_id = 'raft_house';
update tips set node1 = '0x05C', node2 = '0x07F', difficulty = 0 where connection_id = 'tracker-i';
update tips set node1 = 'Raft House', node2 = 'None', difficulty = 0 where connection_id = '3z';
update tips set node1 = 'None', node2 = 'Crazy Tracy''s House', difficulty = 0 where connection_id = '01';
update tips set node1 = 'Outside Manbo', node2 = 'Manbo''s Cave', difficulty = 0 where connection_id = 'mambo';
update tips set node1 = 'Manbo''s Cave', node2 = '0x2FD', difficulty = 0 where connection_id = '3y';
update tips set node1 = 'Manbo''s Cave', node2 = '0x2FD', difficulty = 4 where connection_id = '8r';
update tips set node1 = 'D4 Entrance', node2 = '0x178', difficulty = 0 where connection_id = 'ee';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads East', difficulty = 0 where connection_id = 'eg';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads East', difficulty = 2 where connection_id = 'f5';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads North', difficulty = 2 where connection_id = 'f7';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads South', difficulty = 2 where connection_id = 'f8';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads East', difficulty = 4 where connection_id = 'fh';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads North', difficulty = 4 where connection_id = 'fo';
update tips set node1 = 'D4 Entrance', node2 = 'D4 Crossroads South', difficulty = 4 where connection_id = 'fm';
update tips set node1 = '0x178', node2 = '0x17B', difficulty = 0 where connection_id = 'ef';
update tips set node1 = '0x178', node2 = 'D4 Double Locked Room', difficulty = 0 where connection_id = 'ek';
update tips set node1 = '0x178', node2 = '0x17B', difficulty = 3 where connection_id = 'tracker-z';
update tips set node1 = 'D4 Double Locked Room', node2 = '0x178', difficulty = 0 where connection_id = 'ej';
update tips set node1 = 'D4 Double Locked Room', node2 = 'D4 Crossroads South', difficulty = 0 where connection_id = 'em';
update tips set node1 = 'D4 Crossroads South', node2 = 'D4 Double Locked Room', difficulty = 0 where connection_id = 'el';
update tips set node1 = 'D4 Crossroads South', node2 = 'D4 Double Locked Room', difficulty = 4 where connection_id = 'fk';
update tips set node1 = 'D4 Crossroads South', node2 = '0x175', difficulty = 0 where connection_id = 'en';
update tips set node1 = 'D4 Crossroads South', node2 = 'D4 Crossroads North', difficulty = 0 where connection_id = 'eo';
update tips set node1 = 'D4 Crossroads South', node2 = '0x175', difficulty = 2 where connection_id = 'f9';
update tips set node1 = 'D4 Crossroads South', node2 = '0x175', difficulty = 4 where connection_id = 'fn';
update tips set node1 = 'D4 Crossroads South', node2 = 'D4 Crossroads East', difficulty = 4 where connection_id = 'fi';
update tips set node1 = 'D4 Crossroads North', node2 = 'D4 Before Miniboss', difficulty = 0 where connection_id = 'ep';
update tips set node1 = 'D4 Crossroads North', node2 = 'D4 Before Miniboss', difficulty = 4 where connection_id = 'fq';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x16F-Owl', difficulty = 0 where connection_id = 'eq';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x169', difficulty = 0 where connection_id = 'er';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x16E', difficulty = 0 where connection_id = 'es';
update tips set node1 = 'D4 Before Miniboss', node2 = 'D4 Tile Puzzle', difficulty = 0 where connection_id = 'et';
update tips set node1 = 'D4 Before Miniboss', node2 = 'D4 Miniboss Room', difficulty = 0 where connection_id = 'eu';
update tips set node1 = 'D4 Before Miniboss', node2 = 'D4 After Flippers', difficulty = 0 where connection_id = 'ew';
update tips set node1 = 'D4 Before Miniboss', node2 = 'D4 Before Boss', difficulty = 0 where connection_id = 'f0';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x169', difficulty = 2 where connection_id = 'f4';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x16E', difficulty = 2 where connection_id = 'fa';
update tips set node1 = 'D4 Before Miniboss', node2 = '0x169', difficulty = 3 where connection_id = 'ff';
update tips set node1 = 'D4 Before Miniboss', node2 = 'D4 After Miniboss', difficulty = 3 where connection_id = 'fg';
update tips set node1 = 'D4 Tile Puzzle', node2 = '0x176', difficulty = 0 where connection_id = 'ez';
update tips set node1 = 'D4 Tile Puzzle', node2 = '0x176', difficulty = 2 where connection_id = 'fc';
update tips set node1 = 'D4 Tile Puzzle', node2 = 'D4 Before Boss', difficulty = 2 where connection_id = 'fd';
update tips set node1 = 'D4 Tile Puzzle', node2 = '0x176', difficulty = 4 where connection_id = 'fr';
update tips set node1 = 'D4 Tile Puzzle', node2 = 'D4 Before Boss', difficulty = 4 where connection_id = 'fs';
update tips set node1 = 'D4 After Flippers', node2 = 'D4 Tile Puzzle', difficulty = 0 where connection_id = 'ey';
update tips set node1 = 'D4 Miniboss Room', node2 = 'D4 After Miniboss', difficulty = 0 where connection_id = 'ev';
update tips set node1 = 'D4 After Miniboss', node2 = 'D4 After Flippers', difficulty = 0 where connection_id = 'ex';
update tips set node1 = 'D4 After Miniboss', node2 = 'D4 After Flippers', difficulty = 2 where connection_id = 'fb';
update tips set node1 = 'D4 Before Boss', node2 = 'D4 Boss Room', difficulty = 0 where connection_id = 'f1';
update tips set node1 = 'D4 Boss Room', node2 = '0x166', difficulty = 0 where connection_id = 'f2';
update tips set node1 = 'D4 Crossroads East', node2 = '0x171', difficulty = 0 where connection_id = 'eh';
update tips set node1 = 'D4 Crossroads East', node2 = '0x165', difficulty = 0 where connection_id = 'ei';
update tips set node1 = 'D4 Crossroads East', node2 = '0x165', difficulty = 2 where connection_id = 'f6';
update tips set node1 = 'D4 Crossroads East', node2 = '0x171', difficulty = 3 where connection_id = 'fe';
update tips set node1 = 'D4 Crossroads East', node2 = '0x171', difficulty = 4 where connection_id = 'fj';
update tips set node1 = 'Outside Rooster House', node2 = 'Between Waterfall and Mountain Stairs', difficulty = 4 where connection_id = '8v';
update tips set node1 = 'Outside Rooster House', node2 = '0x00C', difficulty = 0 where connection_id = '4c';
update tips set node1 = 'Outside Rooster House', node2 = 'Bridge Towards D8', difficulty = 0 where connection_id = '4o';
update tips set node1 = 'Outside Rooster House', node2 = 'Unnamed - Outside Rooster House', difficulty = 0 where connection_id = 'rooster_house';
update tips set node1 = 'Outside Rooster House', node2 = 'Bird Cave', difficulty = 0 where connection_id = 'bird_cave';
update tips set node1 = 'Outside Rooster House', node2 = '0x00C', difficulty = 4 where connection_id = '8y';
update tips set node1 = 'Bridge Towards D8', node2 = 'Path to West Tal Tal Entrance', difficulty = 0 where connection_id = 'left_to_right_taltalentrance';
update tips set node1 = 'Path to West Tal Tal Entrance', node2 = 'Path to West Tal Tal Exit', difficulty = 0 where connection_id = '4q';
update tips set node1 = 'Path to West Tal Tal Entrance', node2 = '0x2BA', difficulty = 0 where connection_id = '4s';
update tips set node1 = 'Path to West Tal Tal Exit', node2 = 'Falling Rocks', difficulty = 0 where connection_id = 'left_taltal_entrance';
update tips set node1 = 'Falling Rocks', node2 = 'Outside Fire Cave', difficulty = 0 where connection_id = '4w';
update tips set node1 = 'Falling Rocks', node2 = 'Mountain Mad Batter', difficulty = 0 where connection_id = 'madbatter_taltal';
update tips set node1 = 'Outside Fire Cave', node2 = 'Fire Cave South', difficulty = 0 where connection_id = 'fire_cave_entrance';
update tips set node1 = 'Fire Cave South', node2 = 'Fire Cave North', difficulty = 0 where connection_id = '4x';
update tips set node1 = 'Fire Cave South', node2 = 'Fire Cave North', difficulty = 2 where connection_id = 'tracker-y';
update tips set node1 = 'Fire Cave North', node2 = 'Fire Cave South', difficulty = 2 where connection_id = 'tracker-x';
update tips set node1 = 'Fire Cave North', node2 = 'Outside D8', difficulty = 0 where connection_id = 'fire_cave_exit';
update tips set node1 = 'Outside D8', node2 = 'D8 Entrance', difficulty = 0 where connection_id = 'd8';
update tips set node1 = 'Outside D8', node2 = 'Unnamed - Outside D8', difficulty = 0 where connection_id = 'phone_d8';
update tips set node1 = 'D8 Entrance', node2 = 'D8 North of Entrance', difficulty = 0 where connection_id = 'jj';
update tips set node1 = 'D8 Entrance', node2 = 'D8 After Hinox', difficulty = 0 where connection_id = 'jk';
update tips set node1 = 'D8 Entrance', node2 = '0x253-Owl', difficulty = 0 where connection_id = 'jp';
update tips set node1 = 'D8 Entrance', node2 = '0x259', difficulty = 0 where connection_id = 'jq';
update tips set node1 = 'D8 Entrance', node2 = '0x25A', difficulty = 0 where connection_id = 'jr';
update tips set node1 = 'D8 Entrance', node2 = '0x258', difficulty = 0 where connection_id = 'tracker-m';
update tips set node1 = 'D8 Entrance', node2 = 'D8 North of Entrance', difficulty = 4 where connection_id = 'l1';
update tips set node1 = 'D8 Entrance', node2 = '0x253-Owl', difficulty = 4 where connection_id = 'l2';
update tips set node1 = 'D8 Entrance', node2 = '0x25F', difficulty = 4 where connection_id = 'l4';
update tips set node1 = '0x25F', node2 = 'D8 Entrance', difficulty = 4 where connection_id = 'l3';
update tips set node1 = 'D8 North of Entrance', node2 = '0x24F', difficulty = 0 where connection_id = 'jt';
update tips set node1 = 'D8 North of Entrance', node2 = 'D8 After Lava Keyblock', difficulty = 0 where connection_id = 'ju';
update tips set node1 = 'D8 North of Entrance', node2 = '0x240', difficulty = 0 where connection_id = 'k6';
update tips set node1 = 'D8 North of Entrance', node2 = 'D8 Before Cueball', difficulty = 0 where connection_id = 'ke';
update tips set node1 = 'D8 North of Entrance', node2 = 'D8 Before Boss Door', difficulty = 0 where connection_id = 'ki';
update tips set node1 = 'D8 North of Entrance', node2 = 'D8 After Lava Keyblock', difficulty = 3 where connection_id = 'kt';
update tips set node1 = 'D8 North of Entrance', node2 = '0x25F', difficulty = 3 where connection_id = 'ks';
update tips set node1 = 'D8 North of Entrance', node2 = 'D8 Before Boss Door', difficulty = 4 where connection_id = 'lc';
update tips set node1 = '0x25F', node2 = 'D8 North of Entrance', difficulty = 4 where connection_id = 'lb';
update tips set node1 = '0x24F', node2 = 'D8 Before Cueball', difficulty = 4 where connection_id = 'l9';
update tips set node1 = 'D8 After Lava Keyblock', node2 = 'hidden_arrow_room', difficulty = 0 where connection_id = 'jv';
update tips set node1 = 'D8 After Lava Keyblock', node2 = '0x240', difficulty = 2 where connection_id = 'kp';
update tips set node1 = 'D8 After Lava Keyblock', node2 = '0x240', difficulty = 3 where connection_id = 'kw';
update tips set node1 = 'D8 After Lava Keyblock', node2 = 'D8 Miniboss Stairs', difficulty = 3 where connection_id = 'kv';
update tips set node1 = 'D8 After Lava Keyblock', node2 = '0x240', difficulty = 4 where connection_id = 'l8';
update tips set node1 = 'hidden_arrow_room', node2 = '0x245-Owl', difficulty = 0 where connection_id = 'jw';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x23E', difficulty = 0 where connection_id = 'jx';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x235', difficulty = 0 where connection_id = 'jy';
update tips set node1 = 'D8 Dodongo Area', node2 = 'D8 Dark East', difficulty = 0 where connection_id = 'jz';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x240', difficulty = 0 where connection_id = 'k5';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x23E2', difficulty = 0 where connection_id = 'tracker-n';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x23E', difficulty = 2 where connection_id = 'ko';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x235', difficulty = 3 where connection_id = 'kz';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x240', difficulty = 3 where connection_id = 'kx';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x23E', difficulty = 4 where connection_id = 'l5';
update tips set node1 = 'D8 Dodongo Area', node2 = '0x235', difficulty = 4 where connection_id = 'l6';
update tips set node1 = '0x240', node2 = 'D8 Dodongo Area', difficulty = 0 where connection_id = 'k9';
update tips set node1 = '0x235', node2 = '0x2352', difficulty = 0 where connection_id = 'tracker-o';
update tips set node1 = 'D8 Dark East', node2 = 'D8 Dark Center', difficulty = 0 where connection_id = 'k0';
update tips set node1 = 'D8 Dark Center', node2 = 'D8 Dark West', difficulty = 0 where connection_id = 'k1';
update tips set node1 = 'D8 Dark Center', node2 = '0x240', difficulty = 0 where connection_id = 'kh';
update tips set node1 = 'D8 Dark West', node2 = 'D8 Miniboss Stairs', difficulty = 0 where connection_id = 'k2';
update tips set node1 = 'D8 Miniboss Stairs', node2 = 'D8 Miniboss Room', difficulty = 0 where connection_id = 'k3';
update tips set node1 = 'D8 Miniboss Stairs', node2 = 'D8 Miniboss Room', difficulty = 4 where connection_id = 'l7';
update tips set node1 = 'D8 Miniboss Room', node2 = '0x237', difficulty = 0 where connection_id = 'k4';
update tips set node1 = '0x240', node2 = 'D8 After Hinox', difficulty = 0 where connection_id = 'k7';
update tips set node1 = '0x240', node2 = '0x23D', difficulty = 0 where connection_id = 'k8';
update tips set node1 = '0x240', node2 = '0x000', difficulty = 0 where connection_id = 'ka';
update tips set node1 = '0x240', node2 = '0x241', difficulty = 0 where connection_id = 'kb';
update tips set node1 = '0x240', node2 = '0x241-Owl', difficulty = 0 where connection_id = 'kc';
update tips set node1 = '0x240', node2 = '0x23A', difficulty = 0 where connection_id = 'kd';
update tips set node1 = '0x240', node2 = '0x24C', difficulty = 2 where connection_id = 'km';
update tips set node1 = '0x240', node2 = 'D8 Before Cueball', difficulty = 3 where connection_id = 'ky';
update tips set node1 = '0x240', node2 = 'D8 Before Boss Door', difficulty = 3 where connection_id = 'l0';
update tips set node1 = 'D8 Before Cueball', node2 = '0x240', difficulty = 0 where connection_id = 'kf';
update tips set node1 = 'D8 After Hinox', node2 = '0x25C', difficulty = 0 where connection_id = 'jl';
update tips set node1 = 'D8 After Hinox', node2 = '0x255', difficulty = 0 where connection_id = 'jn';
update tips set node1 = 'D8 After Hinox', node2 = '0x246', difficulty = 0 where connection_id = 'jo';
update tips set node1 = 'D8 After Hinox', node2 = '0x255', difficulty = 3 where connection_id = 'kr';
update tips set node1 = '0x25C', node2 = '0x24C', difficulty = 0 where connection_id = 'jm';
update tips set node1 = 'D8 Before Cueball', node2 = '0x232', difficulty = 0 where connection_id = 'kg';
update tips set node1 = 'D8 Before Cueball', node2 = '0x232', difficulty = 4 where connection_id = 'la';
update tips set node1 = 'D8 Before Boss Door', node2 = 'D8 Boss Room', difficulty = 0 where connection_id = 'kj';
update tips set node1 = 'D8 Boss Room', node2 = '0x234', difficulty = 0 where connection_id = 'kk';
update tips set node1 = '0x259', node2 = '0x25A', difficulty = 2 where connection_id = 'kn';
update tips set node1 = '0x25A', node2 = '0x25F', difficulty = 0 where connection_id = 'js';
update tips set node1 = 'Mountain Mad Batter', node2 = '0x1E2', difficulty = 0 where connection_id = '4t';
update tips set node1 = 'Bird Cave', node2 = 'BirdPits', difficulty = 1 where connection_id = 'tracker-t';
update tips set node1 = 'Bird Cave', node2 = '0x27A', difficulty = 4 where connection_id = '8z';
update tips set node1 = 'Unnamed - Lower Tal Tal,5 Chest Game Tunnel', node2 = '5 Chest Game Tunnel', difficulty = 0 where connection_id = 'multichest_left';
update tips set node1 = '5 Chest Game Tunnel', node2 = 'To 5 Chest Game', difficulty = 0 where connection_id = '4e';
update tips set node1 = '5 Chest Game Tunnel', node2 = 'Near Hole to Damp Cave', difficulty = 0 where connection_id = 'multichest_right';
update tips set node1 = 'To 5 Chest Game', node2 = '5 Chest Game Tunnel', difficulty = 0 where connection_id = '4d';
update tips set node1 = 'To 5 Chest Game', node2 = '0x01D', difficulty = 0 where connection_id = 'multichest_top';
update tips set node1 = 'Near Hole to Damp Cave', node2 = 'Outer Rainbow Cave', difficulty = 0 where connection_id = 'right_taltal_connector1';
update tips set node1 = 'Near Hole to Damp Cave', node2 = 'DampPit', difficulty = 1 where connection_id = 'tracker-v';
update tips set node1 = 'Outer Rainbow Cave', node2 = 'Rainbow Ledge', difficulty = 0 where connection_id = 'right_taltal_connector2';
update tips set node1 = 'Rainbow Ledge', node2 = 'Inner Rainbow Cave Entrance', difficulty = 0 where connection_id = 'right_taltal_connector3';
update tips set node1 = 'D7 Plateau', node2 = 'Rainbow Ledge', difficulty = 1 where connection_id = '4n';
update tips set node1 = 'Inner Rainbow Cave Entrance', node2 = 'Inner Rainbow Cave Exit', difficulty = 0 where connection_id = '4h';
update tips set node1 = 'Inner Rainbow Cave Entrance', node2 = 'Inner Rainbow Cave Exit', difficulty = 2 where connection_id = '5q';
update tips set node1 = 'Inner Rainbow Cave Exit', node2 = 'After Rainbow Caves', difficulty = 0 where connection_id = 'right_taltal_connector4';
update tips set node1 = 'After Rainbow Caves', node2 = 'Path to D7', difficulty = 0 where connection_id = 'right_taltal_connector5';
update tips set node1 = 'After Rainbow Caves', node2 = 'Unnamed - After Rainbow Caves', difficulty = 0 where connection_id = 'right_fairy';
update tips set node1 = 'Path to D7', node2 = 'D7 Plateau', difficulty = 0 where connection_id = 'right_taltal_connector6';
update tips set node1 = 'D7 Plateau', node2 = '0x00E', difficulty = 0 where connection_id = '4i';
update tips set node1 = 'D7 Plateau', node2 = 'D7 Tower', difficulty = 0 where connection_id = '4j';
update tips set node1 = 'D7 Plateau', node2 = 'DampPit', difficulty = 1 where connection_id = 'tracker-w';
update tips set node1 = 'D7 Tower', node2 = 'D7 Plateau', difficulty = 0 where connection_id = '4k';
update tips set node1 = 'D7 Tower', node2 = 'D7 Entrance', difficulty = 0 where connection_id = 'd7';
update tips set node1 = 'D7 Entrance', node2 = '0x210', difficulty = 0 where connection_id = 'ij';
update tips set node1 = 'D7 Entrance', node2 = 'D7 Ball Room', difficulty = 0 where connection_id = 'ik';
update tips set node1 = 'D7 Entrance', node2 = 'D7 Ball Room', difficulty = 3 where connection_id = 'j4';
update tips set node1 = 'D7 Entrance', node2 = 'D7 Ball Room', difficulty = 4 where connection_id = 'jf';
update tips set node1 = 'D7 Ball Room', node2 = '0x216-Owl', difficulty = 0 where connection_id = 'il';
update tips set node1 = 'D7 Ball Room', node2 = '0x212', difficulty = 0 where connection_id = 'im';
update tips set node1 = 'D7 Ball Room', node2 = '0x204-Owl', difficulty = 0 where connection_id = 'in';
update tips set node1 = 'D7 Ball Room', node2 = '0x211', difficulty = 0 where connection_id = 'io';
update tips set node1 = 'D7 Ball Room', node2 = 'D7 Hinox Area', difficulty = 0 where connection_id = 'ip';
update tips set node1 = 'D7 Ball Room', node2 = '0x204', difficulty = 3 where connection_id = 'j5';
update tips set node1 = 'D7 Ball Room', node2 = 'D7 Tile Room', difficulty = 3 where connection_id = 'j6';
update tips set node1 = 'D7 Ball Room', node2 = '0x204', difficulty = 4 where connection_id = 'jg';
update tips set node1 = 'D7 Hinox Area', node2 = '0x201', difficulty = 0 where connection_id = 'iq';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21B', difficulty = 0 where connection_id = 'ir';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21C-Owl', difficulty = 0 where connection_id = 'is';
update tips set node1 = 'D7 Hinox Area', node2 = '0x224', difficulty = 0 where connection_id = 'it';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21A', difficulty = 0 where connection_id = 'iv';
update tips set node1 = 'D7 Hinox Area', node2 = '0x204', difficulty = 0 where connection_id = 'iw';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21C', difficulty = 0 where connection_id = 'ix';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21C-Owl', difficulty = 3 where connection_id = 'ja';
update tips set node1 = 'D7 Hinox Area', node2 = '0x21C', difficulty = 3 where connection_id = 'j9';
update tips set node1 = 'D7 Hinox Area', node2 = 'D7 Final Pillar', difficulty = 3 where connection_id = 'jb';
update tips set node1 = '0x201', node2 = 'D7 Hinox Area', difficulty = 3 where connection_id = 'j8';
update tips set node1 = '0x21A', node2 = 'D7 Hinox Area', difficulty = 0 where connection_id = 'iu';
update tips set node1 = 'D7 Tile Room', node2 = '0x201', difficulty = 3 where connection_id = 'j7';
update tips set node1 = '0x21C', node2 = 'D7 Final Pillar', difficulty = 0 where connection_id = 'iy';
update tips set node1 = 'D7 Final Pillar', node2 = 'D7 After Boss Door', difficulty = 0 where connection_id = 'iz';
update tips set node1 = 'D7 Final Pillar', node2 = 'D7 Before Boss', difficulty = 3 where connection_id = 'jc';
update tips set node1 = 'D7 Final Pillar', node2 = 'D7 Before Boss', difficulty = 4 where connection_id = 'jh';
update tips set node1 = 'D7 After Boss Door', node2 = '0x220', difficulty = 0 where connection_id = 'j0';
update tips set node1 = 'D7 After Boss Door', node2 = 'D7 Before Boss', difficulty = 0 where connection_id = 'j1';
update tips set node1 = 'D7 Before Boss', node2 = 'D7 After Boss Door', difficulty = 3 where connection_id = 'jd';
update tips set node1 = 'D7 Before Boss', node2 = '0x223', difficulty = 0 where connection_id = 'j2';
update tips set node1 = '0x28A', node2 = 'Papahl''s Ledge', difficulty = 0 where connection_id = 'papahl_exit';
update tips set node1 = 'Papahl''s Ledge', node2 = '0x019-Trade', difficulty = 0 where connection_id = '3j';
update tips set node1 = 'Moblin Cave', node2 = '0x2E2', difficulty = 0 where connection_id = '0r';
update tips set node1 = 'Graveyard Cave East', node2 = 'Graveyard Cave West', difficulty = 0 where connection_id = '0o';
update tips set node1 = 'Graveyard Cave East', node2 = '0x2DF', difficulty = 0 where connection_id = '0p';
update tips set node1 = 'Graveyard Cave East', node2 = '0x2DF', difficulty = 2 where connection_id = '5c';
update tips set node1 = 'Graveyard Cave East', node2 = 'Graveyard Cave West', difficulty = 4 where connection_id = '7l';
update tips set node1 = 'Graveyard Cave West', node2 = 'Graveyard Cave East', difficulty = 4 where connection_id = '7k';
update tips set node1 = 'Graveyard Cave West', node2 = 'Unnamed - Graveyard Cave West,Ghost Grave', difficulty = 0 where connection_id = 'graveyard_cave_left';
update tips set node1 = 'Unnamed - Graveyard Cave West,Ghost Grave', node2 = 'Ghost Grave', difficulty = 0 where connection_id = '0q';
update tips set node1 = 'Ghost Grave', node2 = '0x074', difficulty = 0 where connection_id = '0m';
update tips set node1 = 'D0 Entrance', node2 = '0x314', difficulty = 0 where connection_id = 'lf';
update tips set node1 = 'D0 Entrance', node2 = '0x30E', difficulty = 0 where connection_id = 'tracker-j';
update tips set node1 = 'D0 Entrance', node2 = '0x314', difficulty = 2 where connection_id = 'lv';
update tips set node1 = '0x314', node2 = '0x308-Owl', difficulty = 0 where connection_id = 'lg';
update tips set node1 = '0x314', node2 = '0x311', difficulty = 0 where connection_id = 'lh';
update tips set node1 = '0x314', node2 = '0x30F', difficulty = 0 where connection_id = 'li';
update tips set node1 = '0x314', node2 = 'D0 Miniboss Room 1', difficulty = 0 where connection_id = 'lj';
update tips set node1 = '0x314', node2 = 'D0 Miniboss Room 2', difficulty = 0 where connection_id = 'll';
update tips set node1 = '0x314', node2 = '0x311', difficulty = 2 where connection_id = 'lw';
update tips set node1 = '0x314', node2 = '0x311', difficulty = 4 where connection_id = 'lz';
update tips set node1 = 'D0 Miniboss Room 1', node2 = '0x302', difficulty = 0 where connection_id = 'lk';
update tips set node1 = 'D0 Miniboss Room 2', node2 = 'D0 After Miniboss 2', difficulty = 0 where connection_id = 'lm';
update tips set node1 = 'D0 After Miniboss 2', node2 = 'Unnamed - D0 After Miniboss 2,0x307,0x306,D0 After 3x3,0x30A-Owl', difficulty = 0 where connection_id = 'ln';
update tips set node1 = 'Unnamed - D0 After Miniboss 2,0x307,0x306,D0 After 3x3,0x30A-Owl', node2 = '0x307', difficulty = 0 where connection_id = 'lo';
update tips set node1 = 'Unnamed - D0 After Miniboss 2,0x307,0x306,D0 After 3x3,0x30A-Owl', node2 = '0x30A-Owl', difficulty = 0 where connection_id = 'lp';
update tips set node1 = 'Unnamed - D0 After Miniboss 2,0x307,0x306,D0 After 3x3,0x30A-Owl', node2 = 'D0 After 3x3', difficulty = 0 where connection_id = 'lq';
update tips set node1 = 'Unnamed - D0 After Miniboss 2,0x307,0x306,D0 After 3x3,0x30A-Owl', node2 = '0x307', difficulty = 4 where connection_id = 'm0';
update tips set node1 = 'D0 After 3x3', node2 = 'D0 Room Before Boss', difficulty = 0 where connection_id = 'lr';
update tips set node1 = 'D0 Room Before Boss', node2 = 'D0 Outside Boss Door', difficulty = 0 where connection_id = 'ls';
update tips set node1 = 'D0 Room Before Boss', node2 = 'D0 Outside Boss Door', difficulty = 2 where connection_id = 'lx';
update tips set node1 = 'D0 Outside Boss Door', node2 = 'D0 Boss Room', difficulty = 0 where connection_id = 'lt';
update tips set node1 = 'D0 Boss Room', node2 = '0x301-0', difficulty = 0 where connection_id = 'lu';
update tips set node1 = 'Outside D3', node2 = 'D3 Entrance', difficulty = 0 where connection_id = 'd3';
update tips set node1 = 'D3 Entrance', node2 = '0x153', difficulty = 0 where connection_id = 'cv';
update tips set node1 = 'D3 Entrance', node2 = 'D3 After Pot Door', difficulty = 0 where connection_id = 'cw';
update tips set node1 = 'D3 Entrance', node2 = '0x153', difficulty = 2 where connection_id = 'dt';
update tips set node1 = 'D3 After Pot Door', node2 = '0x151', difficulty = 0 where connection_id = 'cx';
update tips set node1 = 'D3 After Pot Door', node2 = 'D3 After Zol Chest', difficulty = 0 where connection_id = 'cy';
update tips set node1 = 'D3 After Pot Door', node2 = '0x150', difficulty = 3 where connection_id = 'dy';
update tips set node1 = 'D3 After Pot Door', node2 = '0x150', difficulty = 4 where connection_id = 'e3';
update tips set node1 = 'D3 After Zol Chest', node2 = '0x14E', difficulty = 0 where connection_id = 'cz';
update tips set node1 = 'D3 After Zol Chest', node2 = 'D3 West Room', difficulty = 0 where connection_id = 'dq';
update tips set node1 = 'D3 After Zol Chest', node2 = 'D3 South Room', difficulty = 0 where connection_id = 'dr';
update tips set node1 = 'D3 After Zol Chest', node2 = 'D3 East Room', difficulty = 0 where connection_id = 'd9';
update tips set node1 = 'D3 After Zol Chest', node2 = '0x14E', difficulty = 3 where connection_id = 'e0';
update tips set node1 = 'D3 After Zol Chest', node2 = '0x14C', difficulty = 3 where connection_id = 'dz';
update tips set node1 = 'D3 After Zol Chest', node2 = '0x14C', difficulty = 4 where connection_id = 'e4';
update tips set node1 = 'D3 North Room', node2 = '0x14E', difficulty = 4 where connection_id = 'e5';
update tips set node1 = 'D3 North Room', node2 = '0x154', difficulty = 2 where connection_id = 'du';
update tips set node1 = 'D3 North Room', node2 = '0x14C', difficulty = 2 where connection_id = 'dw';
update tips set node1 = 'D3 North Room', node2 = '0x150', difficulty = 2 where connection_id = 'dx';
update tips set node1 = 'D3 West Room', node2 = '0x155', difficulty = 0 where connection_id = 'd6';
update tips set node1 = 'D3 West Room', node2 = '0x155', difficulty = 4 where connection_id = 'e6';
update tips set node1 = 'D3 South Room', node2 = '0x158', difficulty = 2 where connection_id = 'dv';
update tips set node1 = 'D3 South Room', node2 = '0x158', difficulty = 4 where connection_id = 'e7';
update tips set node1 = 'D3 East Room', node2 = '0x14D', difficulty = 0 where connection_id = 'da';
update tips set node1 = 'D3 East Room', node2 = '0x147', difficulty = 0 where connection_id = 'db';
update tips set node1 = 'D3 East Room', node2 = 'D3 Miniboss Room', difficulty = 0 where connection_id = 'dc';
update tips set node1 = 'D3 East Room', node2 = '0x142', difficulty = 0 where connection_id = 'de';
update tips set node1 = 'D3 East Room', node2 = '0x148', difficulty = 0 where connection_id = 'dg';
update tips set node1 = 'D3 East Room', node2 = '0x144', difficulty = 0 where connection_id = 'dh';
update tips set node1 = 'D3 East Room', node2 = '0x140-Owl', difficulty = 0 where connection_id = 'di';
update tips set node1 = 'D3 East Room', node2 = 'D3 Boss Path 1', difficulty = 0 where connection_id = 'dj';
update tips set node1 = 'D3 East Room', node2 = '0x141', difficulty = 2 where connection_id = 'ds';
update tips set node1 = 'D3 East Room', node2 = '0x147', difficulty = 3 where connection_id = 'e1';
update tips set node1 = 'D3 East Room', node2 = '0x146', difficulty = 3 where connection_id = 'e2';
update tips set node1 = 'D3 East Room', node2 = '0x147', difficulty = 4 where connection_id = 'e9';
update tips set node1 = 'D3 Miniboss Room', node2 = '0x146', difficulty = 0 where connection_id = 'dd';
update tips set node1 = '0x142', node2 = '0x141', difficulty = 0 where connection_id = 'df';
update tips set node1 = '0x142', node2 = '0x141', difficulty = 4 where connection_id = 'ea';
update tips set node1 = 'D3 Boss Path 1', node2 = 'D3 Boss Path 2', difficulty = 0 where connection_id = 'dk';
update tips set node1 = 'D3 Boss Path 2', node2 = 'D3 Boss Path 3', difficulty = 0 where connection_id = 'dl';
update tips set node1 = 'D3 Boss Path 3', node2 = 'D3 Boss Path 4', difficulty = 0 where connection_id = 'dm';
update tips set node1 = 'D3 Boss Path 4', node2 = 'Unnamed - D3 Boss Room,D3 Boss Path 4,D3 BEFORE NIGHTMARE', difficulty = 0 where connection_id = 'dn';
update tips set node1 = 'D3 Boss Path 4', node2 = 'Unnamed - D3 Boss Room,D3 Boss Path 4,D3 BEFORE NIGHTMARE', difficulty = 4 where connection_id = 'ec';
update tips set node1 = 'Unnamed - D3 Boss Room,D3 Boss Path 4,D3 BEFORE NIGHTMARE', node2 = 'D3 Boss Room', difficulty = 0 where connection_id = 'do';
update tips set node1 = 'D3 Boss Room', node2 = '0x15A', difficulty = 0 where connection_id = 'dp';
update tips set node1 = 'Animal Village', node2 = '0x0CD-Trade', difficulty = 0 where connection_id = '2h';
update tips set node1 = 'Animal Village', node2 = 'Inside Mermaid Statue', difficulty = 0 where connection_id = '2k';
update tips set node1 = 'Animal Village', node2 = '0x0DA', difficulty = 0 where connection_id = '2q';
update tips set node1 = 'Animal Village', node2 = 'Desert', difficulty = 0 where connection_id = '2r';
update tips set node1 = 'Animal Village', node2 = 'Armos Maze', difficulty = 0 where connection_id = '2y';
update tips set node1 = 'Animal Village', node2 = 'Under the River East', difficulty = 0 where connection_id = 'animal_to_prairie_connector';
update tips set node1 = 'Animal Village', node2 = 'Unnamed - Animal Village', difficulty = 0 where connection_id = 'animal_phone';
update tips set node1 = 'Animal Village', node2 = 'Goat''s House', difficulty = 0 where connection_id = 'animal_house3';
update tips set node1 = 'Animal Village', node2 = 'Bear Chef''s House', difficulty = 0 where connection_id = 'animal_house5';
update tips set node1 = 'Animal Village', node2 = 'RiverRooster', difficulty = 0 where connection_id = 'tracker-p';
update tips set node1 = 'Desert', node2 = '0x0CE', difficulty = 0 where connection_id = '2s';
update tips set node1 = 'Desert', node2 = 'Desert Cave', difficulty = 0 where connection_id = 'desert_cave';
update tips set node1 = 'Desert', node2 = '0x0FF', difficulty = 0 where connection_id = '2x';
update tips set node1 = 'Desert', node2 = 'Bomb Arrow Cave', difficulty = 0 where connection_id = 'animal_cave';
update tips set node1 = 'Desert', node2 = 'LanmolaPit', difficulty = 0 where connection_id = 'tracker-u';
update tips set node1 = 'Desert Cave', node2 = '0x1E8', difficulty = 0 where connection_id = '2w';
update tips set node1 = 'Bomb Arrow Cave', node2 = '0x2E6', difficulty = 0 where connection_id = '2u';
update tips set node1 = 'Bomb Arrow Cave', node2 = '0x2E6', difficulty = 2 where connection_id = '5i';
update tips set node1 = 'Bomb Arrow Cave', node2 = '0x2E6', difficulty = 3 where connection_id = '6i';
update tips set node1 = 'Armos Maze', node2 = 'Outside Armos Maze Cave', difficulty = 2 where connection_id = '5k';
update tips set node1 = 'Armos Maze', node2 = 'Outside Southern Shrine', difficulty = 2 where connection_id = '5l';
update tips set node1 = 'Outside Armos Maze Cave', node2 = '0x2FC', difficulty = 0 where connection_id = 'armos_maze_cave';
update tips set node1 = 'Outside Southern Shrine', node2 = 'Southern Shrine', difficulty = 0 where connection_id = 'armos_temple';
update tips set node1 = 'Southern Shrine', node2 = '0x27F', difficulty = 0 where connection_id = '2z';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Unnamed - Outside D6 Fairy', difficulty = 0 where connection_id = 'armos_fairy';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Raft Exit', difficulty = 3 where connection_id = '6n';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Armos Island', difficulty = 3 where connection_id = '6m';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Raft Exit', difficulty = 4 where connection_id = '8g';
update tips set node1 = 'Outside D6 Fairy', node2 = 'Armos Island', difficulty = 4 where connection_id = '8f';
update tips set node1 = 'Outside D6', node2 = 'Outside D6 Fairy', difficulty = 3 where connection_id = '6k';
update tips set node1 = 'Outside D6', node2 = 'Outside D6 Fairy', difficulty = 4 where connection_id = '8e';
update tips set node1 = 'Raft Exit', node2 = 'Raft Return South', difficulty = 0 where connection_id = 'raft_return_enter';
update tips set node1 = 'Under the River East', node2 = 'Under the River West', difficulty = 0 where connection_id = '2o';
update tips set node1 = 'Goat''s House', node2 = '0x2D9-Trade', difficulty = 0 where connection_id = '2j';
update tips set node1 = 'Bear Chef''s House', node2 = '0x2D7-Trade', difficulty = 0 where connection_id = '2i';
update tips set node1 = 'Seashell Mansion', node2 = '0x2E9-0', difficulty = 0 where connection_id = '1o';
update tips set node1 = 'Seashell Mansion', node2 = '0x2E9-1', difficulty = 0 where connection_id = '1p';
update tips set node1 = 'Seashell Mansion', node2 = '0x2E9', difficulty = 0 where connection_id = '1q';
update tips set node1 = 'Bay Cliff Cave', node2 = 'Bay Cliff to Plateau', difficulty = 0 where connection_id = '1j';
update tips set node1 = 'Bay Cliff Cave', node2 = 'Bay Cliff to Plateau', difficulty = 4 where connection_id = '7o';
update tips set node1 = 'Bay Cliff to Plateau', node2 = 'Bay Cliff Cave', difficulty = 0 where connection_id = '1i';
update tips set node1 = 'Bay Cliff to Plateau', node2 = 'Bay Plateau', difficulty = 0 where connection_id = 'prairie_right_cave_high';
update tips set node1 = 'Bay Plateau', node2 = '0x0A8', difficulty = 0 where connection_id = '1h';
update tips set node1 = 'Richard''s Villa', node2 = 'Richard''s Cave', difficulty = 0 where connection_id = '1w';
update tips set node1 = 'Richard''s Cave', node2 = 'Richard''s Villa', difficulty = 0 where connection_id = '1x';
update tips set node1 = 'Richard''s Cave', node2 = '0x2C8', difficulty = 0 where connection_id = '1y';
update tips set node1 = 'Richard''s Cave', node2 = 'Pothole Maze', difficulty = 0 where connection_id = 'richard_maze';
update tips set node1 = 'Richard''s Cave', node2 = '0x2C8', difficulty = 4 where connection_id = '7p';
update tips set node1 = 'Pothole Maze', node2 = 'Near Slime Key', difficulty = 0 where connection_id = '1z';
update tips set node1 = 'Outside D5', node2 = 'D5 Entrance', difficulty = 0 where connection_id = 'd5';
update tips set node1 = 'D5 Entrance', node2 = '0x1A0', difficulty = 0 where connection_id = 'fu';
update tips set node1 = 'D5 Entrance', node2 = '0x19E', difficulty = 0 where connection_id = 'fv';
update tips set node1 = 'D5 Entrance', node2 = 'D5 After First Key', difficulty = 0 where connection_id = 'fx';
update tips set node1 = 'D5 Entrance', node2 = '0x1A0', difficulty = 3 where connection_id = 'gu';
update tips set node1 = 'D5 Entrance', node2 = '0x1A0', difficulty = 4 where connection_id = 'h0';
update tips set node1 = '0x19E', node2 = '0x181', difficulty = 0 where connection_id = 'fw';
update tips set node1 = '0x19E', node2 = '0x181', difficulty = 4 where connection_id = 'h1';
update tips set node1 = 'D5 After First Key', node2 = '0x19A-Owl', difficulty = 0 where connection_id = 'fy';
update tips set node1 = 'D5 After First Key', node2 = '0x19B', difficulty = 0 where connection_id = 'fz';
update tips set node1 = 'D5 After First Key', node2 = '0x196', difficulty = 0 where connection_id = 'g7';
update tips set node1 = '0x19B', node2 = '0x197', difficulty = 0 where connection_id = 'g0';
update tips set node1 = '0x19B', node2 = 'D5 Before Miniboss', difficulty = 0 where connection_id = 'g1';
update tips set node1 = '0x19B', node2 = '0x197', difficulty = 2 where connection_id = 'gk';
update tips set node1 = '0x19B', node2 = '0x197', difficulty = 4 where connection_id = 'h2';
update tips set node1 = '0x19B', node2 = 'D5 Before Miniboss', difficulty = 4 where connection_id = 'h3';
update tips set node1 = 'D5 Before Miniboss', node2 = 'D5 Miniboss Room', difficulty = 0 where connection_id = 'g2';
update tips set node1 = 'D5 Before Miniboss', node2 = 'D5 After Miniboss', difficulty = 3 where connection_id = 'gv';
update tips set node1 = 'D5 Before Miniboss', node2 = 'D5 After Miniboss', difficulty = 4 where connection_id = 'h4';
update tips set node1 = 'D5 Miniboss Room', node2 = 'D5 After Miniboss', difficulty = 0 where connection_id = 'g3';
update tips set node1 = 'D5 After Miniboss', node2 = 'D5 Before Boss Keyblock', difficulty = 0 where connection_id = 'g4';
update tips set node1 = 'D5 After Miniboss', node2 = 'D5 Before Boss Keyblock', difficulty = 2 where connection_id = 'gp';
update tips set node1 = 'D5 After Miniboss', node2 = 'D5 Before Boss Keyblock', difficulty = 4 where connection_id = 'h5';
update tips set node1 = 'D5 Before Boss Keyblock', node2 = 'D5 After Boss Keyblock', difficulty = 0 where connection_id = 'g5';
update tips set node1 = 'D5 Before Boss Keyblock', node2 = '0x196', difficulty = 3 where connection_id = 'gz';
update tips set node1 = 'D5 Before Boss Keyblock', node2 = '0x196', difficulty = 4 where connection_id = 'h7';
update tips set node1 = '0x196', node2 = 'D5 Before Boss Keyblock', difficulty = 0 where connection_id = 'g8';
update tips set node1 = '0x196', node2 = 'D5 Before Boss Keyblock', difficulty = 2 where connection_id = 'go';
update tips set node1 = 'D5 After Boss Keyblock', node2 = 'D5 Before Boss', difficulty = 0 where connection_id = 'gg';
update tips set node1 = 'D5 After Boss Keyblock', node2 = '0x196', difficulty = 2 where connection_id = 'gs';
update tips set node1 = 'D5 After Boss Keyblock', node2 = '0x18A-Owl', difficulty = 4 where connection_id = 'hg';
update tips set node1 = 'D5 Before Boss', node2 = 'D5 Boss Room', difficulty = 0 where connection_id = 'gh';
update tips set node1 = 'D5 Before Boss', node2 = '0x196', difficulty = 2 where connection_id = 'gt';
update tips set node1 = 'D5 Before Boss', node2 = '0x196', difficulty = 4 where connection_id = 'hh';
update tips set node1 = 'D5 Boss Room', node2 = '0x185', difficulty = 0 where connection_id = 'gi';
update tips set node1 = '0x196', node2 = 'D5 Crossroads North', difficulty = 0 where connection_id = 'g9';
update tips set node1 = '0x196', node2 = '0x186', difficulty = 0 where connection_id = 'gf';
update tips set node1 = '0x196', node2 = '0x18A-Owl', difficulty = 2 where connection_id = 'gn';
update tips set node1 = '0x196', node2 = 'D5 Crossroads North', difficulty = 2 where connection_id = 'gq';
update tips set node1 = '0x196', node2 = '0x186', difficulty = 2 where connection_id = 'gl';
update tips set node1 = '0x196', node2 = '0x186', difficulty = 4 where connection_id = 'hf';
update tips set node1 = 'D5 Crossroads North', node2 = '0x18E', difficulty = 0 where connection_id = 'ga';
update tips set node1 = 'D5 Crossroads North', node2 = '0x188', difficulty = 0 where connection_id = 'gb';
update tips set node1 = 'D5 Crossroads North', node2 = '0x18F', difficulty = 0 where connection_id = 'gc';
update tips set node1 = 'D5 Crossroads North', node2 = 'D5 Master Stalfos 3', difficulty = 0 where connection_id = 'gd';
update tips set node1 = 'D5 Crossroads North', node2 = '0x183', difficulty = 0 where connection_id = 'ge';
update tips set node1 = 'D5 Crossroads North', node2 = '0x18E', difficulty = 2 where connection_id = 'gr';
update tips set node1 = 'D5 Crossroads North', node2 = '0x188', difficulty = 3 where connection_id = 'gw';
update tips set node1 = 'D5 Crossroads North', node2 = '0x18E', difficulty = 4 where connection_id = 'ha';
update tips set node1 = 'D5 Crossroads North', node2 = '0x188', difficulty = 4 where connection_id = 'h9';
update tips set node1 = '0x18E', node2 = '0x18F', difficulty = 3 where connection_id = 'gx';
update tips set node1 = '0x18E', node2 = '0x18F', difficulty = 4 where connection_id = 'hb';
update tips set node1 = 'D5 Master Stalfos 3', node2 = '0x180', difficulty = 0 where connection_id = 'gj';
update tips set node1 = 'D5 Master Stalfos 3', node2 = '0x180', difficulty = 4 where connection_id = 'he';
update tips set node1 = 'Armos Island', node2 = 'To D6 East', difficulty = 0 where connection_id = 'd6_connector_entrance';
update tips set node1 = 'To D6 East', node2 = 'To D6 West', difficulty = 2 where connection_id = '5m';
update tips set node1 = 'To D6 East', node2 = 'To D6 West', difficulty = 3 where connection_id = '6l';
update tips set node1 = 'To D6 East', node2 = 'To D6 West', difficulty = 4 where connection_id = '8c';
update tips set node1 = 'To D6 West', node2 = 'Outside D6', difficulty = 0 where connection_id = 'd6_connector_exit';
update tips set node1 = 'D6 Entrance', node2 = '0x1CF', difficulty = 0 where connection_id = 'hj';
update tips set node1 = 'D6 Entrance', node2 = '0x1C9', difficulty = 0 where connection_id = 'hk';
update tips set node1 = 'D6 Entrance', node2 = '0x1BB-Owl', difficulty = 0 where connection_id = 'hl';
update tips set node1 = 'D6 Entrance', node2 = '0x1CE', difficulty = 0 where connection_id = 'hm';
update tips set node1 = 'D6 Entrance', node2 = '0x1C0', difficulty = 0 where connection_id = 'hn';
update tips set node1 = 'D6 Entrance', node2 = '0x1B9', difficulty = 0 where connection_id = 'ho';
update tips set node1 = 'D6 Entrance', node2 = 'D6 Before Miniboss', difficulty = 0 where connection_id = 'hs';
update tips set node1 = 'D6 Entrance', node2 = '0x1BE', difficulty = 0 where connection_id = 'hv';
update tips set node1 = 'D6 Entrance', node2 = '0x1CE', difficulty = 2 where connection_id = 'i4';
update tips set node1 = 'D6 Entrance', node2 = '0x1C9', difficulty = 3 where connection_id = 'i7';
update tips set node1 = 'D6 Entrance', node2 = '0x1B9', difficulty = 3 where connection_id = 'i8';
update tips set node1 = 'D6 Entrance', node2 = '0x1B9', difficulty = 4 where connection_id = 'ie';
update tips set node1 = '0x1B9', node2 = '0x1B4', difficulty = 0 where connection_id = 'hp';
update tips set node1 = '0x1B9', node2 = '0x1B0', difficulty = 0 where connection_id = 'hq';
update tips set node1 = '0x1B0', node2 = '0x06C', difficulty = 0 where connection_id = 'hr';
update tips set node1 = 'D6 Before Miniboss', node2 = 'D6 Miniboss Room', difficulty = 0 where connection_id = 'ht';
update tips set node1 = 'D6 Miniboss Room', node2 = 'D6 After Miniboss', difficulty = 0 where connection_id = 'hu';
update tips set node1 = 'D6 After Miniboss', node2 = '0x1C3', difficulty = 0 where connection_id = 'hy';
update tips set node1 = 'D6 After Miniboss', node2 = '0x1C3', difficulty = 2 where connection_id = 'i5';
update tips set node1 = 'D6 After Miniboss', node2 = '0x1C3', difficulty = 3 where connection_id = 'ia';
update tips set node1 = 'D6 After Miniboss', node2 = '0x1C3', difficulty = 4 where connection_id = 'ig';
update tips set node1 = '0x1C3', node2 = '0x1B1', difficulty = 0 where connection_id = 'hz';
update tips set node1 = '0x1C3', node2 = 'D6 Boss Room', difficulty = 0 where connection_id = 'i2';
update tips set node1 = '0x1C3', node2 = '0x1B1', difficulty = 2 where connection_id = 'i6';
update tips set node1 = '0x1B1', node2 = '0x1C3', difficulty = 3 where connection_id = 'ib';
update tips set node1 = '0x1B1', node2 = '0x1B6', difficulty = 0 where connection_id = 'i0';
update tips set node1 = '0x1BE', node2 = '0x1B1', difficulty = 3 where connection_id = 'i9';
update tips set node1 = '0x1BE', node2 = '0x1B1', difficulty = 4 where connection_id = 'ih';
update tips set node1 = '0x1B6', node2 = '0x1B6-Owl', difficulty = 0 where connection_id = 'i1';
update tips set node1 = '0x1B6', node2 = '0x1BE', difficulty = 3 where connection_id = 'ic';
update tips set node1 = 'D6 Boss Room', node2 = '0x1BC', difficulty = 0 where connection_id = 'i3';
update tips set node1 = '0x1BE', node2 = '0x1D1', difficulty = 0 where connection_id = 'hw';
update tips set node1 = '0x1BE', node2 = '0x1D7-Owl', difficulty = 0 where connection_id = 'hx';
update tips set node1 = '0x1BE', node2 = '0x1D1', difficulty = 4 where connection_id = 'if';
update tips set node1 = 'Ghost House', node2 = '0x1E3', difficulty = 0 where connection_id = 'v';
update tips set node1 = 'Boomerang Cave', node2 = '0x1F5', difficulty = 0 where connection_id = 'r';
update tips set node1 = 'Papahl House', node2 = '0x2A6-Trade', difficulty = 3 where connection_id = '5s';
update tips set node1 = 'Shop', node2 = '0x2A1-0', difficulty = 0 where connection_id = 'd';
update tips set node1 = 'Shop', node2 = '0x2A1-1', difficulty = 0 where connection_id = 'e';
update tips set node1 = 'Kennel', node2 = '0x2B2', difficulty = 0 where connection_id = 'l';
update tips set node1 = 'Kennel', node2 = '0x2B2-Trade', difficulty = 0 where connection_id = 'm';
update tips set node1 = 'Trendy Shop', node2 = '0x2A0', difficulty = 0 where connection_id = 'tracker-g';
update tips set node1 = 'D1 Entrance', node2 = '0x116', difficulty = 0 where connection_id = 'b9';
update tips set node1 = 'D1 Entrance', node2 = '0x10D', difficulty = 0 where connection_id = 'ba';
update tips set node1 = 'D1 Entrance', node2 = '0x114', difficulty = 0 where connection_id = 'bb';
update tips set node1 = 'D1 Entrance', node2 = '0x10C', difficulty = 0 where connection_id = 'bc';
update tips set node1 = 'D1 Entrance', node2 = 'D1 Upper Left', difficulty = 0 where connection_id = 'bd';
update tips set node1 = 'D1 Entrance', node2 = '0x108', difficulty = 0 where connection_id = 'bg';
update tips set node1 = 'D1 Entrance', node2 = 'D1 Right Side', difficulty = 0 where connection_id = 'bh';
update tips set node1 = 'D1 Entrance', node2 = '0x114', difficulty = 2 where connection_id = 'bo';
update tips set node1 = 'D1 Entrance', node2 = '0x108', difficulty = 3 where connection_id = 'bq';
update tips set node1 = 'D1 Entrance', node2 = '0x108', difficulty = 4 where connection_id = 'bt';
update tips set node1 = 'D1 Upper Left', node2 = '0x103-Owl', difficulty = 0 where connection_id = 'be';
update tips set node1 = 'D1 Upper Left', node2 = '0x11D', difficulty = 0 where connection_id = 'bf';
update tips set node1 = 'D1 Upper Left', node2 = '0x11D', difficulty = 4 where connection_id = 'bs';
update tips set node1 = 'D1 Right Side', node2 = '0x10A-Owl', difficulty = 0 where connection_id = 'bi';
update tips set node1 = 'D1 Right Side', node2 = '0x10A', difficulty = 0 where connection_id = 'bj';
update tips set node1 = 'D1 Right Side', node2 = 'D1 Miniboss Room', difficulty = 0 where connection_id = 'bk';
update tips set node1 = 'D1 Right Side', node2 = 'D1 Miniboss Room', difficulty = 3 where connection_id = 'br';
update tips set node1 = 'D1 Miniboss Room', node2 = 'D1 After Miniboss', difficulty = 0 where connection_id = 'bl';
update tips set node1 = 'D1 After Miniboss', node2 = 'D1 Boss Room', difficulty = 0 where connection_id = 'bm';
update tips set node1 = 'D1 Boss Room', node2 = '0x106', difficulty = 0 where connection_id = 'bn';
update tips set node1 = 'Hookshot Cave', node2 = '0x2B3', difficulty = 0 where connection_id = '07';
update tips set node1 = 'Forest Mad Batter', node2 = '0x1E1', difficulty = 0 where connection_id = '03';
update tips set node1 = 'Witch''s Hut', node2 = '0x2A2', difficulty = 0 where connection_id = 'z';
update tips set node1 = 'Witch''s Hut', node2 = '0x2A22', difficulty = 0 where connection_id = 'tracker-h';
